<?php

namespace Bigfoot\Bundle\ImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSourceRepository extends EntityRepository
{
}
